"""add password reset token table

Revision ID: 94c0b7e4794a
Revises: d7b45543f0a9
Create Date: 2025-09-23 16:30:31.774225

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94c0b7e4794a"
down_revision: Union[str, Sequence[str], None] = "d7b45543f0a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "password_reset_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_token_id"), "password_reset_token", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_password_reset_token_token"),
        "password_reset_token",
        ["token"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_password_reset_token_token"), table_name="password_reset_token"
    )
    op.drop_index(op.f("ix_password_reset_token_id"), table_name="password_reset_token")
    op.drop_table("password_reset_token")
    # ### end Alembic commands ###
